apiVersion: v1
kind: Service
metadata:
  name: filebox-api-gateway-service
  labels: 
    name: filebox-api-gateway-service
spec:
  selector:
    app: filebox-api-gateway
  type: LoadBalancer
  ports:
    - port: 3000